// Automatically generated by astro-icon
// 4846b63e06c67a71db9a3397510a8056ca72a311204e3ae1ca1de50c0c0efbcc

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "ion:bookmark-outline"
		| "ion:information-circle-outline"
		| "ion:notifications-outline"
		| "ion:checkbox-outline"
		| "ion:warning-outline"
		| "ion:alert-circle-outline"
		| "mdi:email"
		| "mdi:linkedin"
		| "teenyicons:vr-headset-outline"
		| "load"
		| "logo"
		| "scholar";
}