// Automatically generated by astro-icon
// 4ae418bb38eda4322ec1bf1e709216b580cebc7333981fdf9c4328655702c1c4

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "ion:bookmark-outline"
		| "ion:information-circle-outline"
		| "ion:notifications-outline"
		| "ion:checkbox-outline"
		| "ion:warning-outline"
		| "ion:alert-circle-outline"
		| "mdi:email"
		| "mdi:linkedin"
		| "teenyicons:vr-headset-outline"
		| "logo"
		| "scholar";
}